export const sendCountryCodes = [
  {cc: '+1', country: 'United States'},
  {cc: '+1', country: 'Canada'},
  {cc: '+1', country: 'Caribbean'},
  {cc: '+7', country: 'Kazakhstan'},
  {cc: '+7', country: 'Russia'},
  {cc: '+20', country: 'Egypt'},
  {cc: '+27', country: 'South Africa'},
  {cc: '+30', country: 'Greece'},
  {cc: '+31', country: 'Netherlands'},
  {cc: '+32', country: 'Belgium'},
  {cc: '+33', country: 'France'},
  {cc: '+34', country: 'Spain'},
  {cc: '+36', country: 'Hungary'},
  {cc: '+39', country: 'Italy'},
  {cc: '+40', country: 'Romania'},
  {cc: '+41', country: 'Switzerland'},
  {cc: '+43', country: 'Austria'},
  {cc: '+44', country: 'United Kingdom'},
  {cc: '+45', country: 'Denmark'},
  {cc: '+46', country: 'Sweden'},
  {cc: '+47', country: 'Norway'},
  {cc: '+48', country: 'Poland'},
  {cc: '+49', country: 'Germany'},
  {cc: '+51', country: 'Peru'},
  {cc: '+52', country: 'Mexico'},
  {cc: '+53', country: 'Cuba'},
  {cc: '+54', country: 'Argentina'},
  {cc: '+55', country: 'Brazil'},
  {cc: '+56', country: 'Chile'},
  {cc: '+57', country: 'Colombia'},
  {cc: '+58', country: 'Venezuela'},
  {cc: '+60', country: 'Malaysia'},
  {cc: '+61', country: 'Australia'},
  {cc: '+62', country: 'Indonesia'},
  {cc: '+63', country: 'Philippines'},
  {cc: '+64', country: 'New Zealand'},
  {cc: '+65', country: 'Singapore'},
  {cc: '+66', country: 'Thailand'},
  {cc: '+81', country: 'Japan'},
  {cc: '+82', country: 'South Korea'},
  {cc: '+84', country: 'Vietnam'},
  {cc: '+86', country: 'China'},
  {cc: '+90', country: 'Turkey'},
  {cc: '+91', country: 'India'},
  {cc: '+92', country: 'Pakistan'},
  {cc: '+93', country: 'Afghanistan'},
  {cc: '+94', country: 'Sri Lanka'},
  {cc: '+95', country: 'Myanmar'},
  {cc: '+98', country: 'Iran'},
  {cc: '+211', country: 'South Sudan'},
  {cc: '+212', country: 'Morocco'},
  {cc: '+213', country: 'Algeria'},
  {cc: '+216', country: 'Tunisia'},
  {cc: '+218', country: 'Libya'},
  {cc: '+220', country: 'Gambia'},
  {cc: '+221', country: 'Senegal'},
  {cc: '+222', country: 'Mauritania'},
  {cc: '+223', country: 'Mali'},
  {cc: '+224', country: 'Guinea'},
  {cc: '+225', country: 'Ivory Coast'},
  {cc: '+226', country: 'Burkina Faso'},
  {cc: '+227', country: 'Niger'},
  {cc: '+228', country: 'Togo'},
  {cc: '+229', country: 'Benin'},
  {cc: '+230', country: 'Mauritius'},
  {cc: '+231', country: 'Liberia'},
  {cc: '+232', country: 'Sierra Leone'},
  {cc: '+233', country: 'Ghana'},
  {cc: '+234', country: 'Nigeria'},
  {cc: '+235', country: 'Chad'},
  {cc: '+236', country: 'Central African Republic'},
  {cc: '+237', country: 'Cameroon'},
  {cc: '+238', country: 'Cape Verde'},
  {cc: '+239', country: 'Sao Tome and Principe'},
  {cc: '+240', country: 'Equatorial Guinea'},
  {cc: '+241', country: 'Gabon'},
  {cc: '+242', country: 'Republic of the Congo'},
  {cc: '+243', country: 'Democratic Republic of the Congo'},
  {cc: '+244', country: 'Angola'},
  {cc: '+245', country: 'Guinea-Bissau'},
  {cc: '+246', country: 'British Indian Ocean Territory'},
  {cc: '+248', country: 'Seychelles'},
  {cc: '+249', country: 'Sudan'},
  {cc: '+250', country: 'Rwanda'},
  {cc: '+251', country: 'Ethiopia'},
  {cc: '+252', country: 'Somalia'},
  {cc: '+253', country: 'Djibouti'},
  {cc: '+254', country: 'Kenya'},
  {cc: '+255', country: 'Tanzania'},
  {cc: '+256', country: 'Uganda'},
  {cc: '+257', country: 'Burundi'},
  {cc: '+258', country: 'Mozambique'},
  {cc: '+260', country: 'Zambia'},
  {cc: '+261', country: 'Madagascar'},
  {cc: '+262', country: 'Mayotte'},
  {cc: '+262', country: 'Reunion'},
  {cc: '+263', country: 'Zimbabwe'},
  {cc: '+264', country: 'Namibia'},
  {cc: '+265', country: 'Malawi'},
  {cc: '+266', country: 'Lesotho'},
  {cc: '+267', country: 'Botswana'},
  {cc: '+268', country: 'Eswatini'},
  {cc: '+269', country: 'Comoros'},
  {cc: '+290', country: 'Saint Helena'},
  {cc: '+291', country: 'Eritrea'},
  {cc: '+297', country: 'Aruba'},
  {cc: '+298', country: 'Faroe Islands'},
  {cc: '+299', country: 'Greenland'},
  {cc: '+350', country: 'Gibraltar'},
  {cc: '+351', country: 'Portugal'},
  {cc: '+352', country: 'Luxembourg'},
  {cc: '+353', country: 'Ireland'},
  {cc: '+354', country: 'Iceland'},
  {cc: '+355', country: 'Albania'},
  {cc: '+356', country: 'Malta'},
  {cc: '+357', country: 'Cyprus'},
  {cc: '+358', country: 'Finland'},
  {cc: '+359', country: 'Bulgaria'},
  {cc: '+370', country: 'Lithuania'},
  {cc: '+371', country: 'Latvia'},
  {cc: '+372', country: 'Estonia'},
  {cc: '+373', country: 'Moldova'},
  {cc: '+374', country: 'Armenia'},
  {cc: '+375', country: 'Belarus'},
  {cc: '+376', country: 'Andorra'},
  {cc: '+377', country: 'Monaco'},
  {cc: '+378', country: 'San Marino'},
  {cc: '+379', country: 'Vatican City'},
  {cc: '+380', country: 'Ukraine'},
  {cc: '+381', country: 'Serbia'},
  {cc: '+382', country: 'Montenegro'},
  {cc: '+383', country: 'Kosovo'},
  {cc: '+385', country: 'Croatia'},
  {cc: '+386', country: 'Slovenia'},
  {cc: '+387', country: 'Bosnia and Herzegovina'},
  {cc: '+389', country: 'North Macedonia'},
  {cc: '+420', country: 'Czech Republic'},
  {cc: '+421', country: 'Slovakia'},
  {cc: '+423', country: 'Liechtenstein'},
  {cc: '+500', country: 'Falkland Islands'},
  {cc: '+501', country: 'Belize'},
  {cc: '+502', country: 'Guatemala'},
  {cc: '+503', country: 'El Salvador'},
  {cc: '+504', country: 'Honduras'},
  {cc: '+505', country: 'Nicaragua'},
  {cc: '+506', country: 'Costa Rica'},
  {cc: '+507', country: 'Panama'},
  {cc: '+508', country: 'Saint Pierre and Miquelon'},
  {cc: '+509', country: 'Haiti'},
  {cc: '+590', country: 'Guadeloupe'},
  {cc: '+590', country: 'Saint Barthélemy'},
  {cc: '+590', country: 'Saint Martin'},
  {cc: '+591', country: 'Bolivia'},
  {cc: '+592', country: 'Guyana'},
  {cc: '+593', country: 'Ecuador'},
  {cc: '+594', country: 'French Guiana'},
  {cc: '+595', country: 'Paraguay'},
  {cc: '+596', country: 'Martinique'},
  {cc: '+597', country: 'Suriname'},
  {cc: '+598', country: 'Uruguay'},
  {cc: '+599', country: 'Curacao'},
  {cc: '+599', country: 'Bonaire'},
  {cc: '+599', country: 'Sint Eustatius'},
  {cc: '+599', country: 'Saba'},
  {cc: '+670', country: 'East Timor'},
  {cc: '+672', country: 'Australian External Territories'},
  {cc: '+673', country: 'Brunei'},
  {cc: '+674', country: 'Nauru'},
  {cc: '+675', country: 'Papua New Guinea'},
  {cc: '+676', country: 'Tonga'},
  {cc: '+677', country: 'Solomon Islands'},
  {cc: '+678', country: 'Vanuatu'},
  {cc: '+679', country: 'Fiji'},
  {cc: '+680', country: 'Palau'},
  {cc: '+681', country: 'Wallis and Futuna'},
  {cc: '+682', country: 'Cook Islands'},
  {cc: '+683', country: 'Niue'},
  {cc: '+685', country: 'Samoa'},
  {cc: '+686', country: 'Kiribati'},
  {cc: '+687', country: 'New Caledonia'},
  {cc: '+688', country: 'Tuvalu'},
  {cc: '+689', country: 'French Polynesia'},
  {cc: '+690', country: 'Tokelau'},
  {cc: '+691', country: 'Federated States of Micronesia'},
  {cc: '+692', country: 'Marshall Islands'},
  {cc: '+850', country: 'North Korea'},
  {cc: '+852', country: 'Hong Kong'},
  {cc: '+853', country: 'Macau'},
  {cc: '+855', country: 'Cambodia'},
  {cc: '+856', country: 'Laos'},
  {cc: '+870', country: 'Inmarsat'},
  {cc: '+880', country: 'Bangladesh'},
  {cc: '+881', country: 'Global Mobile Satellite System'},
  {cc: '+882', country: 'International Networks'},
  {cc: '+883', country: 'International Networks'},
  {cc: '+886', country: 'Taiwan'},
  {cc: '+960', country: 'Maldives'},
  {cc: '+961', country: 'Lebanon'},
  {cc: '+962', country: 'Jordan'},
  {cc: '+963', country: 'Syria'},
  {cc: '+964', country: 'Iraq'},
  {cc: '+965', country: 'Kuwait'},
  {cc: '+966', country: 'Saudi Arabia'},
  {cc: '+967', country: 'Yemen'},
  {cc: '+968', country: 'Oman'},
  {cc: '+970', country: 'Palestine'},
  {cc: '+971', country: 'United Arab Emirates'},
  {cc: '+972', country: 'Israel'},
  {cc: '+973', country: 'Bahrain'},
  {cc: '+974', country: 'Qatar'},
  {cc: '+975', country: 'Bhutan'},
  {cc: '+976', country: 'Mongolia'},
  {cc: '+977', country: 'Nepal'},
  {cc: '+992', country: 'Tajikistan'},
  {cc: '+993', country: 'Turkmenistan'},
  {cc: '+994', country: 'Azerbaijan'},
  {cc: '+995', country: 'Georgia'},
  {cc: '+996', country: 'Kyrgyzstan'},
  {cc: '+998', country: 'Uzbekistan'},
];
