export const sendCountryCodes = [
  {cc: '+1', country: 'United States', isoCode: 'US'},
  {cc: '+1', country: 'Canada', isoCode: 'CA'},
  {cc: '+1', country: 'Caribbean', isoCode: 'CB'},
  {cc: '+7', country: 'Kazakhstan', isoCode: 'KZ'},
  {cc: '+7', country: 'Russia', isoCode: 'RU'},
  {cc: '+20', country: 'Egypt', isoCode: 'EG'},
  {cc: '+27', country: 'South Africa', isoCode: 'ZA'},
  {cc: '+30', country: 'Greece', isoCode: 'GR'},
  {cc: '+31', country: 'Netherlands', isoCode: 'NL'},
  {cc: '+32', country: 'Belgium', isoCode: 'BE'},
  {cc: '+33', country: 'France', isoCode: 'FR'},
  {cc: '+34', country: 'Spain', isoCode: 'ES'},
  {cc: '+36', country: 'Hungary', isoCode: 'HU'},
  {cc: '+39', country: 'Italy', isoCode: 'IT'},
  {cc: '+40', country: 'Romania', isoCode: 'RO'},
  {cc: '+41', country: 'Switzerland', isoCode: 'CH'},
  {cc: '+43', country: 'Austria', isoCode: 'AT'},
  {cc: '+44', country: 'United Kingdom', isoCode: 'GB'},
  {cc: '+45', country: 'Denmark', isoCode: 'DK'},
  {cc: '+46', country: 'Sweden', isoCode: 'SE'},
  {cc: '+47', country: 'Norway', isoCode: 'NO'},
  {cc: '+48', country: 'Poland', isoCode: 'PL'},
  {cc: '+49', country: 'Germany', isoCode: 'DE'},
  {cc: '+51', country: 'Peru', isoCode: 'PE'},
  {cc: '+52', country: 'Mexico', isoCode: 'MX'},
  {cc: '+53', country: 'Cuba', isoCode: 'CU'},
  {cc: '+54', country: 'Argentina', isoCode: 'AR'},
  {cc: '+55', country: 'Brazil', isoCode: 'BR'},
  {cc: '+56', country: 'Chile', isoCode: 'CL'},
  {cc: '+57', country: 'Colombia', isoCode: 'CO'},
  {cc: '+58', country: 'Venezuela', isoCode: 'VE'},
  {cc: '+60', country: 'Malaysia', isoCode: 'MY'},
  {cc: '+61', country: 'Australia', isoCode: 'AU'},
  {cc: '+62', country: 'Indonesia', isoCode: 'ID'},
  {cc: '+63', country: 'Philippines', isoCode: 'PH'},
  {cc: '+64', country: 'New Zealand', isoCode: 'NZ'},
  {cc: '+65', country: 'Singapore', isoCode: 'SG'},
  {cc: '+66', country: 'Thailand', isoCode: 'TH'},
  {cc: '+81', country: 'Japan', isoCode: 'JP'},
  {cc: '+82', country: 'South Korea', isoCode: 'KR'},
  {cc: '+84', country: 'Vietnam', isoCode: 'VN'},
  {cc: '+86', country: 'China', isoCode: 'CN'},
  {cc: '+90', country: 'Turkey', isoCode: 'TR'},
  {cc: '+91', country: 'India', isoCode: 'IN'},
  {cc: '+92', country: 'Pakistan', isoCode: 'PK'},
  {cc: '+93', country: 'Afghanistan', isoCode: 'AF'},
  {cc: '+94', country: 'Sri Lanka', isoCode: 'LK'},
  {cc: '+95', country: 'Myanmar', isoCode: 'MM'},
  {cc: '+98', country: 'Iran', isoCode: 'IR'},
  {cc: '+211', country: 'South Sudan', isoCode: 'SS'},
  {cc: '+212', country: 'Morocco', isoCode: 'MA'},
  {cc: '+213', country: 'Algeria', isoCode: 'DZ'},
  {cc: '+216', country: 'Tunisia', isoCode: 'TN'},
  {cc: '+218', country: 'Libya', isoCode: 'LY'},
  {cc: '+220', country: 'Gambia', isoCode: 'GM'},
  {cc: '+221', country: 'Senegal', isoCode: 'SN'},
  {cc: '+222', country: 'Mauritania', isoCode: 'MR'},
  {cc: '+223', country: 'Mali', isoCode: 'ML'},
  {cc: '+224', country: 'Guinea', isoCode: 'GN'},
  {cc: '+225', country: 'Ivory Coast', isoCode: 'CI'},
  {cc: '+226', country: 'Burkina Faso', isoCode: 'BF'},
  {cc: '+227', country: 'Niger', isoCode: 'NE'},
  {cc: '+228', country: 'Togo', isoCode: 'TG'},
  {cc: '+229', country: 'Benin', isoCode: 'BJ'},
  {cc: '+230', country: 'Mauritius', isoCode: 'MU'},
  {cc: '+231', country: 'Liberia', isoCode: 'LR'},
  {cc: '+232', country: 'Sierra Leone', isoCode: 'SL'},
  {cc: '+233', country: 'Ghana', isoCode: 'GH'},
  {cc: '+234', country: 'Nigeria', isoCode: 'NG'},
  {cc: '+235', country: 'Chad', isoCode: 'TD'},
  {cc: '+236', country: 'Central African Republic', isoCode: 'CF'},
  {cc: '+237', country: 'Cameroon', isoCode: 'CM'},
  {cc: '+238', country: 'Cape Verde', isoCode: 'CV'},
  {cc: '+239', country: 'Sao Tome and Principe', isoCode: 'ST'},
  {cc: '+240', country: 'Equatorial Guinea', isoCode: 'GQ'},
  {cc: '+241', country: 'Gabon', isoCode: 'GA'},
  {cc: '+242', country: 'Republic of the Congo', isoCode: 'CG'},
  {cc: '+243', country: 'Democratic Republic of the Congo', isoCode: 'CD'},
  {cc: '+244', country: 'Angola', isoCode: 'AO'},
  {cc: '+245', country: 'Guinea-Bissau', isoCode: 'GW'},
  {cc: '+246', country: 'British Indian Ocean Territory', isoCode: 'IO'},
  {cc: '+248', country: 'Seychelles', isoCode: 'SC'},
  {cc: '+249', country: 'Sudan', isoCode: 'SD'},
  {cc: '+250', country: 'Rwanda', isoCode: 'RW'},
  {cc: '+251', country: 'Ethiopia', isoCode: 'ET'},
  {cc: '+252', country: 'Somalia', isoCode: 'SO'},
  {cc: '+253', country: 'Djibouti', isoCode: 'DJ'},
  {cc: '+254', country: 'Kenya', isoCode: 'KE'},
  {cc: '+255', country: 'Tanzania', isoCode: 'TZ'},
  {cc: '+256', country: 'Uganda', isoCode: 'UG'},
  {cc: '+257', country: 'Burundi', isoCode: 'BI'},
  {cc: '+258', country: 'Mozambique', isoCode: 'MZ'},
  {cc: '+260', country: 'Zambia', isoCode: 'ZM'},
  {cc: '+261', country: 'Madagascar', isoCode: 'MG'},
  {cc: '+262', country: 'Mayotte', isoCode: 'YT'},
  {cc: '+262', country: 'Reunion', isoCode: 'RE'},
  {cc: '+263', country: 'Zimbabwe', isoCode: 'ZW'},
  {cc: '+264', country: 'Namibia', isoCode: 'NA'},
  {cc: '+265', country: 'Malawi', isoCode: 'MW'},
  {cc: '+266', country: 'Lesotho', isoCode: 'LS'},
  {cc: '+267', country: 'Botswana', isoCode: 'BW'},
  {cc: '+268', country: 'Eswatini', isoCode: 'SZ'},
  {cc: '+269', country: 'Comoros', isoCode: 'KM'},
  {cc: '+290', country: 'Saint Helena', isoCode: 'SH'},
  {cc: '+291', country: 'Eritrea', isoCode: 'ER'},
  {cc: '+965', country: 'Kuwait', isoCode: 'KW'},
  {cc: '+966', country: 'Saudi Arabia', isoCode: 'SA'},
  {cc: '+967', country: 'Yemen', isoCode: 'YE'},
  {cc: '+968', country: 'Oman', isoCode: 'OM'},
  {cc: '+970', country: 'Palestine', isoCode: 'PS'},
  {cc: '+971', country: 'United Arab Emirates', isoCode: 'AE'},
  {cc: '+972', country: 'Israel', isoCode: 'IL'},
  {cc: '+973', country: 'Bahrain', isoCode: 'BH'},
  {cc: '+974', country: 'Qatar', isoCode: 'QA'},
  {cc: '+975', country: 'Bhutan', isoCode: 'BT'},
  {cc: '+976', country: 'Mongolia', isoCode: 'MN'},
  {cc: '+977', country: 'Nepal', isoCode: 'NP'},
  {cc: '+992', country: 'Tajikistan', isoCode: 'TJ'},
  {cc: '+993', country: 'Turkmenistan', isoCode: 'TM'},
  {cc: '+994', country: 'Azerbaijan', isoCode: 'AZ'},
  {cc: '+995', country: 'Georgia', isoCode: 'GE'},
  {cc: '+996', country: 'Kyrgyzstan', isoCode: 'KG'},
  {cc: '+998', country: 'Uzbekistan', isoCode: 'UZ'},
];
