const SATSPERBITCOIN = 100000000;

const LIQUIDAMOUTBUFFER = 1; //sats
const LIGHTNINGAMOUNTBUFFER = 0; //sats
const DUST_LIMIT_FOR_BTC_CHAIN_PAYMENTS = 546;
const DUST_LIMIT_FOR_LBTC_CHAIN_PAYMENTS = 546;

export {
  SATSPERBITCOIN,
  LIQUIDAMOUTBUFFER,
  LIGHTNINGAMOUNTBUFFER,
  DUST_LIMIT_FOR_BTC_CHAIN_PAYMENTS,
  DUST_LIMIT_FOR_LBTC_CHAIN_PAYMENTS,
};
